Show in New WindowClear OutputExpand/Collapse Output
Parsed with column specification:
cols(
  .default = col_double(),
  carrier = col_character(),
  tailnum = col_character(),
  origin = col_character(),
  dest = col_character(),
  time_hour = col_datetime(format = ""),
  name = col_character(),
  dst = col_character(),
  tzone = col_character(),
  type = col_character(),
  manufacturer = col_character(),
  model = col_character(),
  engine = col_character()
)
See spec(...) for full column specifications.
Show in New WindowClear OutputExpand/Collapse Output
Classes ‘spec_tbl_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	200000 obs. of  43 variables:
 $ year.x        : num  2013 2013 2013 2013 2013 ...
 $ month         : num  11 10 12 11 10 11 9 12 11 3 ...
 $ day           : num  7 30 18 20 21 7 29 21 7 31 ...
 $ dep_time      : num  600 1252 1723 2029 1620 ...
 $ sched_dep_time: num  600 1250 1715 2030 1625 ...
 $ dep_delay     : num  0 2 8 -1 -5 -8 -10 -4 0 -8 ...
 $ arr_time      : num  826 1356 2008 2141 1818 ...
 $ sched_arr_time: num  825 1400 2020 2205 1831 ...
 $ arr_delay     : num  1 -4 -12 -24 -13 -18 -10 -16 4 -11 ...
 $ carrier       : Factor w/ 16 levels "9E","AA","AS",..: 15 2 5 15 5 4 6 6 1 13 ...
 $ flight        : Factor w/ 3672 levels "1","2","3","4",..: 1525 147 1400 2343 1860 24 3083 3351 2070 1840 ...
 $ tailnum       : Factor w/ 3957 levels "D942DN","N0EGMQ",..: 1437 1226 836 565 756 2459 204 2890 646 3008 ...
 $ origin        : Factor w/ 3 levels "EWR","JFK","LGA": 3 2 3 1 3 1 1 3 2 3 ...
 $ dest          : Factor w/ 104 levels "ABQ","ACK","ALB",..: 5 12 54 55 33 54 59 59 27 29 ...
 $ air_time      : num  123 44 133 107 90 136 110 118 101 47 ...
 $ distance      : num  762 187 950 711 502 937 725 738 589 214 ...
 $ hour          : num  6 12 17 20 16 9 15 15 16 17 ...
 $ minute        : num  0 50 15 30 25 0 29 30 50 0 ...
 $ time_hour     : POSIXct, format: "2013-11-07 11:00:00" "2013-10-30 16:00:00" "2013-12-18 22:00:00" ...
 $ temp          : num  63 59 34 37 63 ...
 $ dewp          : num  55.9 46.9 17.1 18 41 ...
 $ humid         : num  77.8 64.2 49.5 45.6 44.5 ...
 $ wind_dir      : num  210 240 270 20 160 240 180 190 320 140 ...
 $ wind_speed    : num  13.81 9.21 17.26 5.75 13.81 ...
 $ wind_gust     : num  NA NA 21.9 NA NA ...
 $ precip        : num  0 0 0 0 0 0 0 0 0 0 ...
 $ pressure      : num  1011 1025 1020 1036 1017 ...
 $ visib         : num  10 10 10 10 10 10 10 10 10 10 ...
 $ name          : Factor w/ 100 levels "Akron Canton Regional Airport",..: 37 31 67 17 26 67 32 32 19 79 ...
 $ lat           : num  33.6 42.4 28.4 41.8 42.2 ...
 $ lon           : num  -84.4 -71 -81.3 -87.8 -83.4 ...
 $ alt           : num  1026 19 96 620 645 ...
 $ tz            : num  -5 -5 -5 -6 -5 -5 -6 -6 -5 -5 ...
 $ dst           : Factor w/ 2 levels "A","N": 1 1 1 1 1 1 1 1 1 1 ...
 $ tzone         : Factor w/ 7 levels "America/Anchorage",..: 5 5 5 2 5 5 2 2 5 5 ...
 $ year.y        : num  2001 NA 2002 2006 1992 ...
 $ type          : Factor w/ 3 levels "Fixed wing multi engine",..: 1 NA 1 1 1 1 1 1 1 1 ...
 $ manufacturer  : Factor w/ 35 levels "AGUSTA SPA","AIRBUS",..: 10 NA 2 10 3 2 18 11 11 3 ...
 $ model         : Factor w/ 126 levels "150","172E","172M",..: 37 NA 80 37 84 88 106 98 99 79 ...
 $ engines       : num  2 NA 2 2 2 2 2 2 2 2 ...
 $ seats         : num  140 NA 145 140 182 200 55 80 95 179 ...
 $ speed         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ engine        : Factor w/ 6 levels "4 Cycle","Reciprocating",..: 3 NA 3 3 4 3 3 3 3 3 ...
 - attr(*, "spec")=
  .. cols(
  ..   year.x = col_double(),
  ..   month = col_double(),
  ..   day = col_double(),
  ..   dep_time = col_double(),
  ..   sched_dep_time = col_double(),
  ..   dep_delay = col_double(),
  ..   arr_time = col_double(),
  ..   sched_arr_time = col_double(),
  ..   arr_delay = col_double(),
  ..   carrier = col_character(),
  ..   flight = col_double(),
  ..   tailnum = col_character(),
  ..   origin = col_character(),
  ..   dest = col_character(),
  ..   air_time = col_double(),
  ..   distance = col_double(),
  ..   hour = col_double(),
  ..   minute = col_double(),
  ..   time_hour = col_datetime(format = ""),
  ..   temp = col_double(),
  ..   dewp = col_double(),
  ..   humid = col_double(),
  ..   wind_dir = col_double(),
  ..   wind_speed = col_double(),
  ..   wind_gust = col_double(),
  ..   precip = col_double(),
  ..   pressure = col_double(),
  ..   visib = col_double(),
  ..   name = col_character(),
  ..   lat = col_double(),
  ..   lon = col_double(),
  ..   alt = col_double(),
  ..   tz = col_double(),
  ..   dst = col_character(),
  ..   tzone = col_character(),
  ..   year.y = col_double(),
  ..   type = col_character(),
  ..   manufacturer = col_character(),
  ..   model = col_character(),
  ..   engines = col_double(),
  ..   seats = col_double(),
  ..   speed = col_double(),
  ..   engine = col_character()
  .. )
Show in New WindowClear OutputExpand/Collapse Output
time_hour
<S3: POSIXct>
sched_dep_time
<dbl>
sched_arr_time
<dbl>
tz
<dbl>
2013-11-07 11:00:00	600	825	-5	
2013-10-30 16:00:00	1250	1400	-5	
2013-12-18 22:00:00	1715	2020	-5	
2013-11-21 01:00:00	2030	2205	-6	
2013-10-21 20:00:00	1625	1831	-5	
2013-11-07 14:00:00	900	1157	-5	
2013-09-29 19:00:00	1529	1649	-6	
2013-12-21 20:00:00	1530	1710	-6	
2013-11-07 21:00:00	1650	1906	-5	
2013-03-31 21:00:00	1700	1821	-5	
...
1-10 of 200,000 rows | 1-4 of 5 columns
spec_tbl_df
200000 x 5
sched_arr_time
<dbl>
sched_arr_time_hour
<int>
825	8		
1400	14		
2020	20		
2205	22		
1831	18		
1157	11		
1649	16		
1710	17		
1906	19		
1821	18		
...
1-10 of 200,000 rows
spec_tbl_df
200000 x 2
sched_arr_time
<dbl>
sched_arr_time_hour
<int>
825	8			
1400	14			
2020	20			
2205	22			
1831	18			
1157	11			
1649	16			
1710	17			
1906	19			
1821	18			
...
1-10 of 200,000 rows
Show in New WindowClear OutputExpand/Collapse Output

Attaching package: ‘imputeMissings’

The following object is masked from ‘package:Hmisc’:

    impute

The following object is masked from ‘package:dplyr’:

    compute

$month
[1] 7

$day
[1] 16

$dep_delay
[1] -2

$carrier
[1] "UA"

$flight
[1] "15"

$origin
[1] "EWR"

$dest
[1] "ATL"

$distance
[1] 872

$temp
[1] 57.2

$dewp
[1] 42.8

$humid
[1] 57.69

$wind_dir
[1] 220

$wind_speed
[1] 10.35702

$precip
[1] 0

$pressure
[1] 1017.5

$visib
[1] 10

$name
[1] "Hartsfield Jackson Atlanta Intl"

$lat
[1] 36.09775

$lon
[1] -83.35339

$alt
[1] 433

$tz
[1] -5

$dst
[1] "A"

$tzone
[1] "America/New_York"

$year.y
[1] 2002

$type
[1] "Fixed wing multi engine"

$manufacturer
[1] "BOEING"

$model
[1] "A320-232"

$engines
[1] 2

$seats
[1] 149

$engine
[1] "Turbo-fan"

$sched_arr_time_minute
[1] 30

$sched_arr_time_num_minute
[1] 957

$sched_dep_time_minute
[1] 29

$sched_dep_time_num_minute
[1] 839

$sched_air_time
[1] 139

Show in New WindowClear OutputExpand/Collapse Output

corrplot 0.84 loaded
R Console

Show in New WindowClear OutputExpand/Collapse Output
 
 
month
<dbl>
day
<dbl>
carrier
<fctr>
flight
<fctr>
origin
<fctr>
dest
<fctr>
distance
<dbl>
temp
<dbl>
1	11	7	WN	1716	LGA	ATL	762	62.96	
2	10	30	AA	178	JFK	BOS	187	59.00	
3	12	18	DL	1585	LGA	MCO	950	33.98	
4	11	20	WN	3494	EWR	MDW	711	37.04	
5	10	21	DL	2231	LGA	DTW	502	62.96	
6	11	7	B6	27	EWR	MCO	937	64.40	
6 rows | 1-9 of 43 columns
data.frame
6 x 43
 
 
month
<dbl>
day
<dbl>
carrier
<fctr>
flight
<fctr>
origin
<fctr>
dest
<fctr>
1	1.30322	-0.9929373	WN	1716	LGA	ATL	
2	1.01019	1.6325235	AA	178	JFK	BOS	
3	1.59625	0.2627179	DL	1585	LGA	MCO	
4	1.30322	0.4910188	WN	3494	EWR	MDW	
5	1.01019	0.6051693	DL	2231	LGA	DTW	
6	1.30322	-0.9929373	B6	27	EWR	MCO	
6 rows | 1-7 of 43 columns
data.frame
6 x 43
 
 
month
<dbl>
day
<dbl>
carrier
<fctr>
flight
<fctr>
origin
<fctr>
dest
<fctr>
distance
<dbl>
temp
<dbl>
1	1.30322	-0.9929373	WN	1716	LGA	ATL	-0.3777852	0.3339858	
2	1.01019	1.6325235	AA	178	JFK	BOS	-1.1644742	0.1127815	
3	1.59625	0.2627179	DL	1585	LGA	MCO	-0.1205721	-1.2848272	
4	1.30322	0.4910188	WN	3494	EWR	MDW	-0.4475611	-1.1138966	
5	1.01019	0.6051693	DL	2231	LGA	DTW	-0.7335054	0.3339858	
6	1.30322	-0.9929373	B6	27	EWR	MCO	-0.1383581	0.4144237	
6 rows | 1-9 of 43 columns
Show in New WindowClear OutputExpand/Collapse Output
[1] 8.30571
Show in New WindowClear OutputExpand/Collapse Output
[1] 8.299767
Show in New WindowClear OutputExpand/Collapse Output
[1] 8.469257
Show in New WindowClear OutputExpand/Collapse Output
Analysis of Variance Table

Model 1: dep_delay ~ month + day + carrier + origin + dest + distance + 
    temp + dewp + humid + wind_dir + wind_speed + precip + pressure + 
    visib + name + lat + lon + alt + tz + dst + tzone + year.y + 
    type + manufacturer + model + engines + seats + engine + 
    sched_arr_time_minute + sched_arr_time_num_minute + sched_dep_time_minute + 
    sched_dep_time_num_minute + sched_air_time + dep_delay_flag + 
    temp_flag + wind_dir_flag + wind_speed_flag + precip_flag + 
    pressure_flag + name_flag + year.y_flag + type_flag
Model 2: dep_delay ~ (month + day + carrier + origin + dest + distance + 
    temp + dewp + humid + wind_dir + wind_speed + precip + pressure + 
    visib + name + lat + lon + alt + tz + dst + tzone + year.y + 
    type + manufacturer + model + engines + seats + engine + 
    sched_arr_time_minute + sched_arr_time_num_minute + sched_dep_time_minute + 
    sched_dep_time_num_minute + sched_air_time + dep_delay_flag + 
    temp_flag + wind_dir_flag + wind_speed_flag + precip_flag + 
    pressure_flag + name_flag + year.y_flag + type_flag) - dest
  Res.Df     RSS Df Sum of Sq     F    Pr(>F)    
1 113488 7240975                                 
2 113491 7242239 -3   -1263.7 6.602 0.0001863 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
            Estimate Std. Error    t value Pr(>|t|)
carrierFL   4.615319   0.887510   5.200301        0
carrierUA   2.440853   0.484369   5.039237        0
originJFK   1.037568   0.117779   8.809419        0
wind_speed  0.291278   0.027929  10.429081        0
precip      0.206814   0.029257   7.068777        0
pressure   -0.294549   0.027059 -10.885462        0
Show in New WindowClear OutputExpand/Collapse Output
                                            Estimate Std. Error    t value Pr(>|t|)
carrierAA                                  -2.318607   0.269781  -8.594395 0.000000
carrierAS                                  -3.341812   0.616737  -5.418535 0.000000
carrierDL                                  -1.392992   0.253561  -5.493710 0.000000
carrierEV                                   1.274029   0.187960   6.778204 0.000000
carrierMQ                                  -2.396562   0.272333  -8.800101 0.000000
carrierUS                                  -2.323719   0.260042  -8.935921 0.000000
carrierWN                                   2.796283   0.325335   8.595102 0.000000
originJFK                                   0.831817   0.115446   7.205266 0.000000
wind_speed                                  0.294774   0.027966  10.540539 0.000000
precip                                      0.208324   0.029304   7.109046 0.000000
pressure                                   -0.293555   0.027097 -10.833530 0.000000
year.y                                      0.257028   0.042093   6.106234 0.000000
seats                                       0.365535   0.068252   5.355693 0.000000
sched_arr_time_num_minute                   0.241584   0.045987   5.253282 0.000000
sched_dep_time_minute                       0.132111   0.024902   5.305163 0.000000
sched_dep_time_num_minute                   1.258505   0.044951  27.996992 0.000000
dep_delay_flag1                            -3.014132   0.155718 -19.356329 0.000000
pressure_flag1                              0.606457   0.098873   6.133711 0.000000
carrierHA                                  -4.771275   1.108689  -4.303528 0.000017
destCHO                                   -36.123526   9.266129  -3.898449 0.000097
destILM                                   -31.097284   8.056795  -3.859759 0.000114
destPDX                                    14.661963   3.837985   3.820224 0.000133
destSMF                                    16.425104   4.321366   3.800905 0.000144
destPHX                                     8.055347   2.133058   3.776432 0.000159
destCRW                                   -31.215951   8.376979  -3.726397 0.000194
visib                                      -0.127430   0.034660  -3.676623 0.000236
destSAN                                    13.889006   3.780985   3.673383 0.000239
destJAC                                    11.591104   3.169410   3.657181 0.000255
destSEA                                    13.325506   3.646194   3.654635 0.000258
destLAX                                    14.348648   3.943394   3.638654 0.000274
destCAK                                   -31.214329   8.580927  -3.637640 0.000275
destTUL                                   -13.660070   3.754857  -3.637973 0.000275
destOMA                                   -15.118697   4.158319  -3.635771 0.000277
destSFO                                    16.632081   4.588360   3.624842 0.000289
destBHM                                   -21.009316   5.837679  -3.598916 0.000320
destLGB                                    14.042295   3.939582   3.564412 0.000365
destHNL                                    66.885768  18.771149   3.563222 0.000366
destDSM                                   -17.187039   4.854017  -3.540786 0.000399
destTYS                                   -25.105682   7.108433  -3.531817 0.000413
destBGR                                   -30.575425   8.693169  -3.517178 0.000436
destXNA                                   -14.613857   4.161947  -3.511303 0.000446
destBWI                                   -34.467570   9.818060  -3.510629 0.000447
destLAS                                     9.278585   2.648563   3.503253 0.000460
destAVL                                   -25.975094   7.418111  -3.501578 0.000463
destSNA                                    13.386324   3.822915   3.501601 0.000463
destBDL                                   -35.271411  10.155622  -3.473092 0.000515
destROC                                   -32.435956   9.347846  -3.469886 0.000521
destGSP                                   -25.376154   7.320086  -3.466647 0.000527
destCLE                                   -29.207281   8.425622  -3.466483 0.000528
destRIC                                   -31.792119   9.183695  -3.461800 0.000537
distance                                  -15.049604   4.352182  -3.457945 0.000545
destCVG                                   -25.692606   7.447115  -3.450008 0.000561
destBTV                                   -31.939098   9.300241  -3.434223 0.000594
destDAY                                   -26.344313   7.671046  -3.434253 0.000594
destBOS                                   -33.302948   9.738780  -3.419622 0.000627
destBUF                                   -31.162718   9.124996  -3.415094 0.000638
destSJC                                    15.585073   4.565151   3.413923 0.000641
destOAK                                    15.741470   4.621128   3.406413 0.000658
destPWM                                   -31.438770   9.240920  -3.402126 0.000669
destSLC                                     4.520401   1.329819   3.399261 0.000676
destGRR                                   -24.648547   7.256882  -3.396575 0.000683
destGSO                                   -27.791331   8.186192  -3.394903 0.000687
destIAD                                   -32.407962   9.550812  -3.393215 0.000691
destOKC                                   -10.626435   3.139739  -3.384496 0.000713
destPIT                                   -30.140890   8.909258  -3.383098 0.000717
destDCA                                   -32.545897   9.625597  -3.381182 0.000722
destMCI                                   -14.798414   4.379165  -3.379277 0.000727
destALB                                   -33.767488   9.997762  -3.377505 0.000732
destPHL                                   -34.872031  10.335187  -3.374108 0.000741
destCHS                                   -24.003318   7.115993  -3.373151 0.000743
destIND                                   -23.582074   6.995318  -3.371123 0.000749
destSTL                                   -19.054904   5.660461  -3.366317 0.000762
destPVD                                   -33.332083   9.908856  -3.363868 0.000769
destANC                                    36.554722  10.888763   3.357105 0.000788
destMHT                                   -32.248146   9.615996  -3.353594 0.000798
destSYR                                   -32.442780   9.675578  -3.353059 0.000799
destORF                                   -30.723323   9.167680  -3.351265 0.000805
destCMH                                   -27.023263   8.067612  -3.349599 0.000810
destBNA                                   -21.381935   6.388039  -3.347183 0.000817
destSDF                                   -23.471800   7.027043  -3.340210 0.000837
destRDU                                   -27.895202   8.360245  -3.336649 0.000848
destTVC                                   -23.763734   7.123077  -3.336161 0.000850
destSAV                                   -22.145147   6.646547  -3.331828 0.000863
destMDW                                   -22.017052   6.613415  -3.329150 0.000871
destACK                                   -32.386998   9.753827  -3.320440 0.000899
destMKE                                   -21.556521   6.534602  -3.298827 0.000971
destDTW                                   -26.134652   7.928589  -3.296255 0.000980
destCLT                                   -25.088232   7.674413  -3.269075 0.001079
destJAX                                   -19.502019   5.989172  -3.256213 0.001129
destORD                                   -21.244774   6.565174  -3.235981 0.001213
destMCO                                   -17.147920   5.306618  -3.231422 0.001232
destMSY                                   -12.718760   3.935982  -3.231408 0.001232
destMSN                                   -19.745453   6.122372  -3.225131 0.001260
destMVY                                   -31.958595   9.911091  -3.224528 0.001262
day                                         0.075847   0.023801   3.186663 0.001440
destATL                                   -20.349736   6.406683  -3.176329 0.001492
destRSW                                   -14.406148   4.545223  -3.169514 0.001527
destSRQ                                   -15.035777   4.752239  -3.163935 0.001557
destTPA                                   -15.652896   4.951828  -3.161034 0.001573
destBUR                                    12.507966   3.973579   3.147783 0.001646
destCAE                                   -22.661801   7.428543  -3.050639 0.002284
destMSP                                   -14.801747   4.870956  -3.038776 0.002376
destMEM                                   -15.840986   5.227838  -3.030122 0.002445
destFLL                                   -13.585753   4.566169  -2.975307 0.002928
destMIA                                   -13.114128   4.444244  -2.950812 0.003170
destPSE                                    -4.940578   1.678873  -2.942794 0.003253
destPBI                                   -13.976366   4.805236  -2.908570 0.003632
(Intercept)                                16.474044   5.670479   2.905230 0.003671
destAUS                                    -5.873576   2.038240  -2.881690 0.003956
carrierB6                                  -0.654102   0.227007  -2.881420 0.003960
destDFW                                    -7.889899   2.756116  -2.862688 0.004201
destMYR                                   -21.926351   7.794817  -2.812940 0.004910
originLGA                                  -0.325794   0.115862  -2.811914 0.004926
destIAH                                    -7.258532   2.613026  -2.777827 0.005473
destBQN                                    -4.859601   1.759015  -2.762683 0.005734
destHOU                                    -6.906619   2.546684  -2.712005 0.006689
humid                                       0.417871   0.155521   2.686914 0.007213
manufacturerGULFSTREAM AEROSPACE            8.169688   3.182253   2.567265 0.010252
manufacturerCESSNA                          4.567610   1.811097   2.522013 0.011670
destBZN                                     5.625552   2.281507   2.465718 0.013675
precip_flag1                               -9.363342   3.876804  -2.415222 0.015727
temp_flag1                                  8.517235   3.583399   2.376859 0.017462
carrierYV                                  -1.410746   0.595048  -2.370812 0.017751
manufacturerLEARJET INC                     9.621229   4.098480   2.347511 0.018901
destSAT                                    -4.082388   1.761550  -2.317497 0.020478
carrierUA                                   0.589784   0.254952   2.313314 0.020707
destEYW                                   -11.192190   4.855385  -2.305109 0.021162
carrierFL                                   0.948807   0.417663   2.271705 0.023106
manufacturerMCDONNELL DOUGLAS CORPORATION   7.130518   3.144929   2.267307 0.023373
carrierOO                                  -4.676371   2.080031  -2.248222 0.024564
month                                       0.055963   0.025119   2.227950 0.025886
engineReciprocating                        -4.784441   2.155649  -2.219490 0.026455
engineTurbo-jet                            -7.579155   3.523834  -2.150826 0.031492
manufacturerBOEING                          6.655788   3.121857   2.131996 0.033009
manufacturerBARKER JACK L                   4.156889   1.949770   2.131989 0.033010
manufacturerCANADAIR LTD                   10.020777   4.719325   2.123350 0.033727
manufacturerDEHAVILLAND                     5.277486   2.489152   2.120194 0.033992
destPSP                                     9.000603   4.426308   2.033434 0.042011
manufacturerMCDONNELL DOUGLAS               6.307716   3.121992   2.020414 0.043343
manufacturerPIPER                           4.028235   2.033192   1.981236 0.047567
manufacturerMCDONNELL DOUGLAS AIRCRAFT CO   6.192869   3.126076   1.981036 0.047590
engineTurbo-fan                            -6.970145   3.522649  -1.978666 0.047856
manufacturerPAIR MIKE E                     5.954488   3.056590   1.948082 0.051408
manufacturerCIRRUS DESIGN CORP              3.649312   1.879395   1.941748 0.052170
manufacturerAIRBUS INDUSTRIE                5.928450   3.122708   1.898496 0.057633
destSTT                                    -2.956627   1.572582  -1.880110 0.060096
destSJU                                    -2.898323   1.599828  -1.811647 0.070043
manufacturerEMBRAER                         5.378862   3.116909   1.725704 0.084403
destSBN                                   -15.570339   9.034869  -1.723361 0.084826
manufacturerAIRBUS                          5.285531   3.124349   1.691722 0.090702
wind_dir_flag1                              0.269529   0.159642   1.688332 0.091350
manufacturerLEBLANC GLENN T                 4.512985   2.739959   1.647100 0.099540
destMTJ                                     5.184644   3.150881   1.645458 0.099878
manufacturerFRIEDEMANN JON                  3.889750   2.392071   1.626102 0.103931
manufacturerBOMBARDIER INC                  4.655030   3.120928   1.491553 0.135819
destDEN                                    -2.165776   1.518672  -1.426099 0.153843
manufacturerCANADAIR                        4.355101   3.145879   1.384383 0.166244
manufacturerKILDALL GARY                    2.862667   2.445757   1.170462 0.241817
manufacturerAMERICAN AIRCRAFT INC           3.066792   2.683506   1.142830 0.253112
manufacturerMARZ BARRY                      2.829639   2.587439   1.093606 0.274130
manufacturerAVIONS MARCEL DASSAULT          6.754935   6.699339   1.008299 0.313313
manufacturerBEECH                           3.431401   3.551823   0.966096 0.333998
manufacturerJOHN G HESS                    -4.810782   5.388356  -0.892811 0.371960
manufacturerSIKORSKY                        3.186564   3.678961   0.866159 0.386405
manufacturerBELL                            2.610957   3.284993   0.794814 0.426724
type_flag1                                 -0.203922   0.271119  -0.752150 0.451962
manufacturerDOUGLAS                         4.008806   5.632419   0.711738 0.476629
wind_dir                                    0.018733   0.027026   0.693150 0.488217
sched_arr_time_minute                      -0.013804   0.024404  -0.565633 0.571644
carrierVX                                   0.181052   0.323759   0.559219 0.576013
year.y_flag1                               -0.102593   0.199432  -0.514424 0.606957
manufacturerLAMBERT RICHARD                 1.058252   2.476434   0.427329 0.669141
manufacturerHURLEY JAMES LARRY             -1.997386   4.928047  -0.405310 0.685251
carrierF9                                   0.242613   0.637308   0.380684 0.703438
destHDN                                     1.137227   3.190730   0.356416 0.721530
engines                                    -0.051607   0.146845  -0.351438 0.725260
destEGE                                     0.431238   1.375901   0.313422 0.753960
wind_speed_flag1                            0.449983   1.446992   0.310978 0.755818
typeFixed wing single engine                0.606625   2.103014   0.288455 0.772999
dewp                                        0.040676   0.302037   0.134670 0.892873
manufacturerAVIAT AIRCRAFT INC             -0.501995   3.968705  -0.126488 0.899346
temp                                        0.023006   0.260704   0.088244 0.929683
manufacturerROBINSON HELICOPTER CO          0.248651   3.245307   0.076619 0.938927
typeRotorcraft                             -0.198373   4.095669  -0.048435 0.961370
Show in New WindowClear OutputExpand/Collapse Output
prediction from a rank-deficient fit may be misleading[1] 8.003373
Show in New WindowClear OutputExpand/Collapse Output
Loaded gbm 2.1.5
Distribution not specified, assuming gaussian ...
[1] 8.087401
R Console
 
 
var
<fctr>
sched_dep_time_num_minute	sched_dep_time_num_minute	
model	model	
carrier	carrier	
dest	dest	
sched_arr_time_num_minute	sched_arr_time_num_minute	
origin	origin	
month	month	
dewp	dewp	
precip	precip	
day	day	
1-10 of 42 rows | 1-2 of 2 columns
data.frame
42 x 2

Loaded gbm 2.1.5
Distribution not specified, assuming gaussian ...
[1] 8.087401
Show in New WindowClear OutputExpand/Collapse Output
Distribution not specified, assuming gaussian ...
[1] 7.980812
R Console
 
 
var
<fctr>
sched_dep_time_num_minute	sched_dep_time_num_minute	
model	model	
dest	dest	
carrier	carrier	
month	month	
dewp	dewp	
origin	origin	
sched_arr_time_num_minute	sched_arr_time_num_minute	
precip	precip	
pressure	pressure	
1-10 of 42 rows | 1-2 of 2 columns
data.frame
42 x 2

 
 
var
<fctr>
rel.inf
<dbl>
year.y_flag	year.y_flag	0.00000000	
type_flag	type_flag	0.00000000	
 
 
 
 
 
 
 
 
41-42 of 42 rows
Show in New WindowClear OutputExpand/Collapse Output
[1] 7.980812
Show in New WindowClear OutputExpand/Collapse Output
variable 20: dst has no variation.variable 35: temp_flag has no variation.variable 37: wind_speed_flag has no variation.variable 38: precip_flag has no variation.variable 40: name_flag has no variation.
no loop for break/next, jumping to top level
Show in New WindowClear OutputExpand/Collapse Output
month
<dbl>
day
<dbl>
dep_delay
<dbl>
carrier
<fctr>
flight
<fctr>
origin
<fctr>
dest
<fctr>
distance
<dbl>
temp
<dbl>
dewp
<dbl>
11	7	0	WN	1716	LGA	ATL	762	62.96	55.94	
10	30	2	AA	178	JFK	BOS	187	59.00	46.94	
12	18	8	DL	1585	LGA	MCO	950	33.98	17.06	
11	20	-1	WN	3494	EWR	MDW	711	37.04	17.96	
10	21	-5	DL	2231	LGA	DTW	502	62.96	41.00	
11	7	-8	B6	27	EWR	MCO	937	64.40	55.40	
9	29	-10	EV	4580	EWR	MKE	725	69.08	53.06	
12	21	-4	EV	5207	LGA	MKE	738	57.92	46.04	
11	7	0	9E	2910	JFK	CVG	589	53.60	48.20	
3	31	-8	US	2183	LGA	DCA	214	51.08	35.96	
...
1-10 of 200,000 rows | 1-10 of 37 columns
19  0.75427085 -0.7559493 -0.1492223  1.21581376  0.3664282                 San Francisco Intl
20 -1.95411985 -1.9990552 -0.1492223  0.14516894 -4.3085616      Ronald Reagan Washington Natl
21  0.56081437 -0.3415806 -0.1492223 -2.63850758  0.3664282    Hartsfield Jackson Atlanta Intl
22  1.33464029  1.7302626 -0.1492223 -0.09751055 -0.6177802     Fort Lauderdale Hollywood Intl
23 -0.11628330 -0.7559493 -0.1492223  0.21654527  0.3664282 General Edward Lawrence Logan Intl
24  0.07717317  0.6943410 -0.1492223 -0.98257693  0.3664282                Seattle Tacoma Intl
26 -1.47047866 -0.7559493 -0.1492223  2.58623913  0.3664282                    Palm Beach Intl
          lat         lon         alt         tz dst               tzone      year.y
1  -0.4207546  0.32986743  0.48364704  0.6826595   A    America/New_York -0.08500492
2   1.1190951  1.23783465 -0.60619417  0.6826595   A    America/New_York  0.08617407
3  -1.3395034  0.54085157 -0.52285973  0.6826595   A    America/New_York  0.08617407
4   1.0170501  0.10499769  0.04424731 -0.2514221   A     America/Chicago  0.77089000
5   1.0922942  0.40256211  0.07130394  0.6826595   A    America/New_York -1.62561576
6  -1.3395034  0.54085157 -0.52285973  0.6826595   A    America/New_York  0.77089000
7   1.2219340  0.09524584  0.15572064 -0.2514221   A     America/Chicago -0.08500492
8   1.2219340  0.09524584  0.15572064 -0.2514221   A     America/Chicago  0.42853203
9   0.5341264  0.31364963  0.34295255  0.6826595   A    America/New_York  1.96914288
10  0.4994125  0.82977416 -0.61052323  0.6826595   A    America/New_York -0.25618390
11  0.5157238  0.80149327 -0.28800815  0.6826595   A    America/New_York -0.08500492
12 -0.1424687  0.56559918  0.18277727  0.6826595   A    America/New_York  0.08617407
13 -0.3667981 -1.96864972 -0.49039177 -2.1195851   A America/Los_Angeles  0.77089000
14  1.4909320  1.09253046 -0.26419832  0.6826595   A    America/New_York -0.25618390
17 -1.6475982  0.62293019 -0.60619417  0.6826595   A    America/New_York -0.25618390
18 -0.9752270  0.51522378 -0.59428925  0.6826595   A    America/New_York  1.28442695
19  0.2818499 -2.23697779 -0.61268776 -2.1195851   A America/Los_Angeles -1.28325779
20  0.4994125  0.82977416 -0.61052323  0.6826595   A    America/New_York -0.08500492
21 -0.4207546  0.32986743  0.48364704  0.6826595   A    America/New_York  0.08617407
22 -1.7553248  0.61906363 -0.61701682  0.6826595   A    America/New_York  0.08617407
23  1.1190951  1.23783465 -0.60619417  0.6826595   A    America/New_York  0.77089000
24  2.0162003 -2.23254154 -0.15813631 -2.1195851   A America/Los_Angeles  1.79796390
26 -1.6475982  0.62293019 -0.60619417  0.6826595   A    America/New_York -0.08500492
                      type     manufacturer           model    engines       seats      engine
1  Fixed wing multi engine           BOEING         737-7H4 0.05879311  0.02232546   Turbo-fan
2  Fixed wing multi engine           BOEING        A320-232 0.05879311  0.15869100   Turbo-fan
3  Fixed wing multi engine           AIRBUS        A319-114 0.05879311  0.09808410   Turbo-fan
4  Fixed wing multi engine           BOEING         737-7H4 0.05879311  0.02232546   Turbo-fan
5  Fixed wing multi engine AIRBUS INDUSTRIE        A320-211 0.05879311  0.65869797   Turbo-jet
6  Fixed wing multi engine           AIRBUS        A320-232 0.05879311  0.93142905   Turbo-fan
7  Fixed wing multi engine          EMBRAER       EMB-145LR 0.05879311 -1.26557128   Turbo-fan
8  Fixed wing multi engine   BOMBARDIER INC     CL-600-2C10 0.05879311 -0.88677812   Turbo-fan
9  Fixed wing multi engine   BOMBARDIER INC     CL-600-2D24 0.05879311 -0.65950223   Turbo-fan
10 Fixed wing multi engine AIRBUS INDUSTRIE        A319-112 0.05879311  0.61324279   Turbo-fan
11 Fixed wing multi engine          EMBRAER       EMB-145LR 0.05879311 -1.26557128   Turbo-fan
12 Fixed wing multi engine           BOEING        A320-232 0.05879311  0.15869100   Turbo-fan
13 Fixed wing multi engine           AIRBUS        A320-214 0.05879311  0.65869797   Turbo-fan
14 Fixed wing multi engine          EMBRAER       EMB-145LR 0.05879311 -1.26557128   Turbo-fan
17 Fixed wing multi engine AIRBUS INDUSTRIE        A320-232 0.05879311  0.93142905   Turbo-fan
18 Fixed wing multi engine          EMBRAER ERJ 190-100 IGW 0.05879311 -1.79588171   Turbo-fan
19              Rotorcraft             BELL             230 0.05879311 -1.93224725 Turbo-shaft
20 Fixed wing multi engine          EMBRAER       EMB-145LR 0.05879311 -1.26557128   Turbo-fan
21 Fixed wing multi engine           AIRBUS        A319-114 0.05879311  0.09808410   Turbo-fan
22 Fixed wing multi engine           BOEING        A320-232 0.05879311  0.15869100   Turbo-fan
23 Fixed wing multi engine          EMBRAER ERJ 190-100 IGW 0.05879311 -1.79588171   Turbo-fan
24 Fixed wing multi engine           BOEING       737-990ER 0.05879311  1.26476703   Turbo-fan
26 Fixed wing multi engine AIRBUS INDUSTRIE        A319-114 0.05879311  0.09808410   Turbo-fan
   sched_arr_time_minute sched_arr_time_num_minute sched_dep_time_minute sched_dep_time_num_minute
1            -0.23489378                -1.4325947           -1.36042229               -1.62362934
2            -1.67161447                -0.3129587            1.23408583               -0.16734467
3            -0.52223792                 0.9570761           -0.58206985                0.77391249
4            -1.38427033                 1.3080068            0.19628258                1.46653569
5             0.10991919                 0.5927766           -0.06316823                0.59631680
6             1.60410871                -0.7240489           -1.36042229               -0.98428485
7             1.14435809                 0.2518726            0.14439242                0.39740963
8            -1.09692619                 0.3220587            0.19628258                0.40096154
9            -1.32680151                 0.7097535            1.23408583                0.68511465
10           -0.46476909                 0.5593547           -1.36042229                0.72063379
11           -0.92451971                -0.2695102            1.38975632               -0.15668893
12            1.48917106                 0.4724575            1.49353664                0.48975939
13           -0.52223792                -0.6471784           -0.06316823               -0.89548701
14            1.54663989                -0.1257957            0.71518421                0.01025102
17           -0.17742495                -1.0281889            0.14439242               -1.30750901
18           -1.09692619                 0.3220587            0.45573339                0.20560628
19            0.33979450                -0.7975773           -1.36042229               -1.19739968
20            1.71904637                -1.5194918            1.07841534               -1.45668939
21            0.56966981                -0.5836767            0.19628258               -0.66461261
22            1.48917106                 0.6729894            0.19628258                0.40096154
23           -0.86705088                 1.1375547           -1.36042229                1.35997828
24           -0.80958205                -1.0649530           -1.10097148               -1.39275495
26            0.05245036                -0.4132246           -0.58206985               -0.71789132
   sched_air_time dep_delay_flag temp_flag wind_dir_flag wind_speed_flag precip_flag pressure_flag
1      0.14883297              0         0             0               0           0             0
2     -0.24317221              0         0             0               0           0             0
3      0.35790240              0         0             0               0           0             0
4     -0.11250381              0         0             0               0           0             0
5      0.04952499              0         0             0               0           0             0
6      0.31608852              0         0             0               0           0             1
7     -0.19090485              0         0             0               0           0             0
8     -0.08637014              0         0             0               0           0             0
9      0.10179235              0         0             0               0           0             1
10    -0.18567811              0         0             0               0           0             0
11    -0.19090485              0         0             0               0           0             0
12     0.01816458              0         0             1               0           0             0
13     0.30563504              0         0             0               0           0             0
14    -0.21181179              0         0             0               0           0             0
17     0.31608852              0         0             0               0           0             0
18     0.20110033              0         0             0               0           0             0
19     0.51470447              0         0             0               0           0             0
20    -0.23271874              0         0             0               0           0             0
21     0.06520520              0         0             0               0           0             0
22     0.46243712              0         0             0               0           0             0
23    -0.22226526              0         0             0               0           0             0
24     0.38403608              0         0             0               0           0             0
26     0.41016976              0         0             0               0           0             0
   name_flag year.y_flag type_flag dep_delay
1          0           0         0         0
2          0           1         1         2
3          0           0         0         8
4          0           0         0        -1
5          0           0         0        -5
6          0           0         0        -8
7          0           0         0       -10
8          0           0         0        -4
9          0           0         0         0
10         0           0         0        -8
11         0           0         0        -4
12         0           1         1        11
13         0           0         0        15
14         0           0         0        21
17         0           0         0        -3
18         0           0         0        -6
19         0           0         0         0
20         0           0         0        -4
21         0           1         0        -7
22         0           1         1         3
23         0           0         0        -6
24         0           0         0         7
26         0           0         0         6
 [ reached 'max' / getOption("max.print") -- omitted 170622 rows ]
> colnames(no_duplicate)
 [1] "month"                     "day"                       "carrier"                  
 [4] "origin"                    "dest"                      "distance"                 
 [7] "temp"                      "dewp"                      "humid"                    
[10] "wind_dir"                  "wind_speed"                "precip"                   
[13] "pressure"                  "visib"                     "name"                     
[16] "lat"                       "lon"                       "alt"                      
[19] "tz"                        "dst"                       "tzone"                    
[22] "year.y"                    "type"                      "manufacturer"             
[25] "model"                     "engines"                   "seats"                    
[28] "engine"                    "sched_arr_time_minute"     "sched_arr_time_num_minute"
[31] "sched_dep_time_minute"     "sched_dep_time_num_minute" "sched_air_time"           
[34] "dep_delay_flag"            "temp_flag"                 "wind_dir_flag"            
[37] "wind_speed_flag"           "precip_flag"               "pressure_flag"            
[40] "name_flag"                 "year.y_flag"               "type_flag"                
[43] "dep_delay"                
> colnames(DF)
 [1] "month"                     "day"                       "carrier"                  
 [4] "origin"                    "dest"                      "distance"                 
 [7] "temp"                      "dewp"                      "humid"                    
[10] "wind_dir"                  "wind_speed"                "precip"                   
[13] "pressure"                  "visib"                     "name"                     
[16] "lat"                       "lon"                       "alt"                      
[19] "tz"                        "dst"                       "tzone"                    
[22] "year.y"                    "type"                      "manufacturer"             
[25] "model"                     "engines"                   "seats"                    
[28] "engine"                    "sched_arr_time_minute"     "sched_arr_time_num_minute"
[31] "sched_dep_time_minute"     "sched_dep_time_num_minute" "sched_air_time"           
[34] "dep_delay_flag"            "temp_flag"                 "dewp_flag"                
[37] "humid_flag"                "wind_dir_flag"             "wind_speed_flag"          
[40] "precip_flag"               "pressure_flag"             "visib_flag"               
[43] "name_flag"                 "lat_flag"                  "lon_flag"                 
[46] "alt_flag"                  "tz_flag"                   "dst_flag"                 
[49] "tzone_flag"                "year.y_flag"               "type_flag"                
[52] "manufacturer_flag"         "model_flag"                "engines_flag"             
[55] "seats_flag"                "engine_flag"               "dep_delay"                
> setdiff(colnames(DF), colnames(no_duplicate))
 [1] "dewp_flag"         "humid_flag"        "visib_flag"        "lat_flag"         
 [5] "lon_flag"          "alt_flag"          "tz_flag"           "dst_flag"         
 [9] "tzone_flag"        "manufacturer_flag" "model_flag"        "engines_flag"     
[13] "seats_flag"        "engine_flag"      

Restarting R session...


Restarting R session...

> knitr::opts_chunk$set(echo = TRUE)
> library(tidyverse)
Registered S3 method overwritten by 'dplyr':
  method           from
  print.rowwise_df     
Registered S3 methods overwritten by 'dbplyr':
  method         from
  print.tbl_lazy     
  print.tbl_sql      
── Attaching packages ──────────────────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.2.1     ✔ purrr   0.3.3
✔ tibble  2.1.3     ✔ dplyr   0.8.3
✔ tidyr   1.0.0     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.4.0
── Conflicts ─────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
> library(nycflights13)
> library(Hmisc)
Loading required package: lattice
Loading required package: survival
Loading required package: Formula
Registered S3 methods overwritten by 'htmltools':
  method               from         
  print.html           tools:rstudio
  print.shiny.tag      tools:rstudio
  print.shiny.tag.list tools:rstudio
Registered S3 method overwritten by 'htmlwidgets':
  method           from         
  print.htmlwidget tools:rstudio
Registered S3 method overwritten by 'data.table':
  method           from
  print.data.table     

Attaching package: ‘Hmisc’

The following objects are masked from ‘package:dplyr’:

    src, summarize

The following objects are masked from ‘package:base’:

    format.pval, units

> set.seed(42)
> original_data <- read_csv("fltrain.csv.gz")
Parsed with column specification:
cols(
  .default = col_double(),
  carrier = col_character(),
  tailnum = col_character(),
  origin = col_character(),
  dest = col_character(),
  time_hour = col_datetime(format = ""),
  name = col_character(),
  dst = col_character(),
  tzone = col_character(),
  type = col_character(),
  manufacturer = col_character(),
  model = col_character(),
  engine = col_character()
)
See spec(...) for full column specifications.
> DF <- original_data
> DF[sapply(DF, is.character)] <- lapply(DF[sapply(DF, is.character)], 
+                                        as.factor)
> DF$flight <- as.factor(DF$flight)
> str(DF)
Classes ‘spec_tbl_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	200000 obs. of  43 variables:
 $ year.x        : num  2013 2013 2013 2013 2013 ...
 $ month         : num  11 10 12 11 10 11 9 12 11 3 ...
 $ day           : num  7 30 18 20 21 7 29 21 7 31 ...
 $ dep_time      : num  600 1252 1723 2029 1620 ...
 $ sched_dep_time: num  600 1250 1715 2030 1625 ...
 $ dep_delay     : num  0 2 8 -1 -5 -8 -10 -4 0 -8 ...
 $ arr_time      : num  826 1356 2008 2141 1818 ...
 $ sched_arr_time: num  825 1400 2020 2205 1831 ...
 $ arr_delay     : num  1 -4 -12 -24 -13 -18 -10 -16 4 -11 ...
 $ carrier       : Factor w/ 16 levels "9E","AA","AS",..: 15 2 5 15 5 4 6 6 1 13 ...
 $ flight        : Factor w/ 3672 levels "1","2","3","4",..: 1525 147 1400 2343 1860 24 3083 3351 2070 1840 ...
 $ tailnum       : Factor w/ 3957 levels "D942DN","N0EGMQ",..: 1437 1226 836 565 756 2459 204 2890 646 3008 ...
 $ origin        : Factor w/ 3 levels "EWR","JFK","LGA": 3 2 3 1 3 1 1 3 2 3 ...
 $ dest          : Factor w/ 104 levels "ABQ","ACK","ALB",..: 5 12 54 55 33 54 59 59 27 29 ...
 $ air_time      : num  123 44 133 107 90 136 110 118 101 47 ...
 $ distance      : num  762 187 950 711 502 937 725 738 589 214 ...
 $ hour          : num  6 12 17 20 16 9 15 15 16 17 ...
 $ minute        : num  0 50 15 30 25 0 29 30 50 0 ...
 $ time_hour     : POSIXct, format: "2013-11-07 11:00:00" "2013-10-30 16:00:00" "2013-12-18 22:00:00" ...
 $ temp          : num  63 59 34 37 63 ...
 $ dewp          : num  55.9 46.9 17.1 18 41 ...
 $ humid         : num  77.8 64.2 49.5 45.6 44.5 ...
 $ wind_dir      : num  210 240 270 20 160 240 180 190 320 140 ...
 $ wind_speed    : num  13.81 9.21 17.26 5.75 13.81 ...
 $ wind_gust     : num  NA NA 21.9 NA NA ...
 $ precip        : num  0 0 0 0 0 0 0 0 0 0 ...
 $ pressure      : num  1011 1025 1020 1036 1017 ...
 $ visib         : num  10 10 10 10 10 10 10 10 10 10 ...
 $ name          : Factor w/ 100 levels "Akron Canton Regional Airport",..: 37 31 67 17 26 67 32 32 19 79 ...
 $ lat           : num  33.6 42.4 28.4 41.8 42.2 ...
 $ lon           : num  -84.4 -71 -81.3 -87.8 -83.4 ...
 $ alt           : num  1026 19 96 620 645 ...
 $ tz            : num  -5 -5 -5 -6 -5 -5 -6 -6 -5 -5 ...
 $ dst           : Factor w/ 2 levels "A","N": 1 1 1 1 1 1 1 1 1 1 ...
 $ tzone         : Factor w/ 7 levels "America/Anchorage",..: 5 5 5 2 5 5 2 2 5 5 ...
 $ year.y        : num  2001 NA 2002 2006 1992 ...
 $ type          : Factor w/ 3 levels "Fixed wing multi engine",..: 1 NA 1 1 1 1 1 1 1 1 ...
 $ manufacturer  : Factor w/ 35 levels "AGUSTA SPA","AIRBUS",..: 10 NA 2 10 3 2 18 11 11 3 ...
 $ model         : Factor w/ 126 levels "150","172E","172M",..: 37 NA 80 37 84 88 106 98 99 79 ...
 $ engines       : num  2 NA 2 2 2 2 2 2 2 2 ...
 $ seats         : num  140 NA 145 140 182 200 55 80 95 179 ...
 $ speed         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ engine        : Factor w/ 6 levels "4 Cycle","Reciprocating",..: 3 NA 3 3 4 3 3 3 3 3 ...
 - attr(*, "spec")=
  .. cols(
  ..   year.x = col_double(),
  ..   month = col_double(),
  ..   day = col_double(),
  ..   dep_time = col_double(),
  ..   sched_dep_time = col_double(),
  ..   dep_delay = col_double(),
  ..   arr_time = col_double(),
  ..   sched_arr_time = col_double(),
  ..   arr_delay = col_double(),
  ..   carrier = col_character(),
  ..   flight = col_double(),
  ..   tailnum = col_character(),
  ..   origin = col_character(),
  ..   dest = col_character(),
  ..   air_time = col_double(),
  ..   distance = col_double(),
  ..   hour = col_double(),
  ..   minute = col_double(),
  ..   time_hour = col_datetime(format = ""),
  ..   temp = col_double(),
  ..   dewp = col_double(),
  ..   humid = col_double(),
  ..   wind_dir = col_double(),
  ..   wind_speed = col_double(),
  ..   wind_gust = col_double(),
  ..   precip = col_double(),
  ..   pressure = col_double(),
  ..   visib = col_double(),
  ..   name = col_character(),
  ..   lat = col_double(),
  ..   lon = col_double(),
  ..   alt = col_double(),
  ..   tz = col_double(),
  ..   dst = col_character(),
  ..   tzone = col_character(),
  ..   year.y = col_double(),
  ..   type = col_character(),
  ..   manufacturer = col_character(),
  ..   model = col_character(),
  ..   engines = col_double(),
  ..   seats = col_double(),
  ..   speed = col_double(),
  ..   engine = col_character()
  .. )
> library(lubridate)

Attaching package: ‘lubridate’

The following object is masked from ‘package:base’:

    date

> DF$sched_arr_time_posix <- as.POSIXct(str_pad(as.character(DF$sched_arr_time), 4, pad="0"),format="%H%M")
> DF$sched_arr_time_hour <- hour(DF$sched_arr_time_posix)
> DF$sched_arr_time_minute <- minute(DF$sched_arr_time_posix)
> 
> #num minute is number of minutes since start of day for scheduled arrival time
> DF$sched_arr_time_num_minute <- 60*DF$sched_arr_time_hour + DF$sched_arr_time_minute
> 
> DF$sched_dep_time_posix <- as.POSIXct(str_pad(as.character(DF$sched_dep_time),4 , pad="0"),format="%H%M")
> DF$sched_dep_time_hour <- hour(DF$sched_dep_time_posix)
> DF$sched_dep_time_minute <- minute(DF$sched_dep_time_posix)
> #num minute is number of minutes since start of day for scheduled depival time
> DF$sched_dep_time_num_minute <- 60*DF$sched_dep_time_hour + DF$sched_dep_time_minute
> select(original_data, time_hour, sched_dep_time, sched_arr_time, tz, tzone)
> select(DF, sched_arr_time, sched_arr_time_hour)
> DF$sched_air_time <- DF$sched_arr_time_posix - DF$sched_dep_time_posix
> drops <- c('sched_arr_time_posix', 'sched_arr_time_hour', 'sched_dep_time_posix', 'sched_dep_time_hour', 'sched_dep_time', 'sched_arr_time', 'hour', 'time', 'minute', 'time_hour' )
> DF <- DF[ , !(names(DF) %in% drops)]
> drops <- c("dep_time", "arr_time", "air_time", "arr_delay", "year.x", 'tailnum')
> DF <- DF[ , !(names(DF) %in% drops)]
> DF
> ## Remove columns with more than 50% NA
> DF <- DF[, -which(colMeans(is.na(DF)) > 0.5)]
> DF$sched_air_time <- as.numeric(DF$sched_air_time)
> library(imputeMissings)

Attaching package: ‘imputeMissings’

The following object is masked from ‘package:Hmisc’:

    impute

The following object is masked from ‘package:dplyr’:

    compute

> impute_model <- imputeMissings::compute(DF, method="median/mode")
> impute_model
$month
[1] 7

$day
[1] 16

$dep_delay
[1] -2

$carrier
[1] "UA"

$flight
[1] "15"

$origin
[1] "EWR"

$dest
[1] "ATL"

$distance
[1] 872

$temp
[1] 57.2

$dewp
[1] 42.8

$humid
[1] 57.69

$wind_dir
[1] 220

$wind_speed
[1] 10.35702

$precip
[1] 0

$pressure
[1] 1017.5

$visib
[1] 10

$name
[1] "Hartsfield Jackson Atlanta Intl"

$lat
[1] 36.09775

$lon
[1] -83.35339

$alt
[1] 433

$tz
[1] -5

$dst
[1] "A"

$tzone
[1] "America/New_York"

$year.y
[1] 2002

$type
[1] "Fixed wing multi engine"

$manufacturer
[1] "BOEING"

$model
[1] "A320-232"

$engines
[1] 2

$seats
[1] 149

$engine
[1] "Turbo-fan"

$sched_arr_time_minute
[1] 30

$sched_arr_time_num_minute
[1] 957

$sched_dep_time_minute
[1] 29

$sched_dep_time_num_minute
[1] 839

$sched_air_time
[1] 139

> DF <- impute(DF, object=impute_model, flag=TRUE)
> DF <- DF[!duplicated(as.list(DF))]  #remove all redundant flag columns that are identical to each other. 
> numeric_only_df <- dplyr::select_if(DF, is.numeric)
> library(corrplot)
corrplot 0.84 loaded
> corrplot(cor(numeric_only_df), type = 'lower')
> dep_delay_vec <- DF$dep_delay
> DF$dep_delay <- NULL
> head(DF)
> 
> library(dplyr)
> DF <- DF %>% mutate_if(is.numeric, scale)
> head(DF)
> DF$dep_delay <- dep_delay_vec
> DF<-DF[DF$dep_delay < 30,]
> set.seed(42)
> DF$flight <- NULL
> train_index <- sample(1:nrow(DF),size=2*nrow(DF)/3,replace=FALSE)
> train_df <- DF[train_index,]
> test_df <- DF[-train_index,]
> rmse = mean((test_df$dep_delay-0)^2) %>% sqrt()
> rmse
[1] 8.30571
> rmse = mean((test_df$dep_delay-mean(train_df$dep_delay))^2)%>% sqrt()
> rmse
[1] 8.299767
> rmse = mean((test_df$dep_delay-median(train_df$dep_delay))^2)%>% sqrt()
> rmse
[1] 8.469257
> model <- lm(dep_delay ~ .-model, data=train_df)
> 
> summary <- round(summary(model)$coefficients,6)
> sorteddf <- summary[order(summary[,ncol(summary)]),]
> head(sorteddf)
           Estimate Std. Error   t value Pr(>|t|)
carrierAA -2.318607   0.269781 -8.594395        0
carrierAS -3.341812   0.616737 -5.418535        0
carrierDL -1.392992   0.253561 -5.493710        0
carrierEV  1.274029   0.187960  6.778204        0
carrierMQ -2.396562   0.272333 -8.800101        0
carrierUS -2.323719   0.260042 -8.935921        0
> sorteddf
                                            Estimate Std. Error    t value Pr(>|t|)
carrierAA                                  -2.318607   0.269781  -8.594395 0.000000
carrierAS                                  -3.341812   0.616737  -5.418535 0.000000
carrierDL                                  -1.392992   0.253561  -5.493710 0.000000
carrierEV                                   1.274029   0.187960   6.778204 0.000000
carrierMQ                                  -2.396562   0.272333  -8.800101 0.000000
carrierUS                                  -2.323719   0.260042  -8.935921 0.000000
carrierWN                                   2.796283   0.325335   8.595102 0.000000
originJFK                                   0.831817   0.115446   7.205266 0.000000
wind_speed                                  0.294774   0.027966  10.540539 0.000000
precip                                      0.208324   0.029304   7.109046 0.000000
pressure                                   -0.293555   0.027097 -10.833530 0.000000
year.y                                      0.257028   0.042093   6.106234 0.000000
seats                                       0.365535   0.068252   5.355693 0.000000
sched_arr_time_num_minute                   0.241584   0.045987   5.253282 0.000000
sched_dep_time_minute                       0.132111   0.024902   5.305163 0.000000
sched_dep_time_num_minute                   1.258505   0.044951  27.996992 0.000000
dep_delay_flag1                            -3.014132   0.155718 -19.356329 0.000000
pressure_flag1                              0.606457   0.098873   6.133711 0.000000
carrierHA                                  -4.771275   1.108689  -4.303528 0.000017
destCHO                                   -36.123526   9.266129  -3.898449 0.000097
destILM                                   -31.097284   8.056795  -3.859759 0.000114
destPDX                                    14.661963   3.837985   3.820224 0.000133
destSMF                                    16.425104   4.321366   3.800905 0.000144
destPHX                                     8.055347   2.133058   3.776432 0.000159
destCRW                                   -31.215951   8.376979  -3.726397 0.000194
visib                                      -0.127430   0.034660  -3.676623 0.000236
destSAN                                    13.889006   3.780985   3.673383 0.000239
destJAC                                    11.591104   3.169410   3.657181 0.000255
destSEA                                    13.325506   3.646194   3.654635 0.000258
destLAX                                    14.348648   3.943394   3.638654 0.000274
destCAK                                   -31.214329   8.580927  -3.637640 0.000275
destTUL                                   -13.660070   3.754857  -3.637973 0.000275
destOMA                                   -15.118697   4.158319  -3.635771 0.000277
destSFO                                    16.632081   4.588360   3.624842 0.000289
destBHM                                   -21.009316   5.837679  -3.598916 0.000320
destLGB                                    14.042295   3.939582   3.564412 0.000365
destHNL                                    66.885768  18.771149   3.563222 0.000366
destDSM                                   -17.187039   4.854017  -3.540786 0.000399
destTYS                                   -25.105682   7.108433  -3.531817 0.000413
destBGR                                   -30.575425   8.693169  -3.517178 0.000436
destXNA                                   -14.613857   4.161947  -3.511303 0.000446
destBWI                                   -34.467570   9.818060  -3.510629 0.000447
destLAS                                     9.278585   2.648563   3.503253 0.000460
destAVL                                   -25.975094   7.418111  -3.501578 0.000463
destSNA                                    13.386324   3.822915   3.501601 0.000463
destBDL                                   -35.271411  10.155622  -3.473092 0.000515
destROC                                   -32.435956   9.347846  -3.469886 0.000521
destGSP                                   -25.376154   7.320086  -3.466647 0.000527
destCLE                                   -29.207281   8.425622  -3.466483 0.000528
destRIC                                   -31.792119   9.183695  -3.461800 0.000537
distance                                  -15.049604   4.352182  -3.457945 0.000545
destCVG                                   -25.692606   7.447115  -3.450008 0.000561
destBTV                                   -31.939098   9.300241  -3.434223 0.000594
destDAY                                   -26.344313   7.671046  -3.434253 0.000594
destBOS                                   -33.302948   9.738780  -3.419622 0.000627
destBUF                                   -31.162718   9.124996  -3.415094 0.000638
destSJC                                    15.585073   4.565151   3.413923 0.000641
destOAK                                    15.741470   4.621128   3.406413 0.000658
destPWM                                   -31.438770   9.240920  -3.402126 0.000669
destSLC                                     4.520401   1.329819   3.399261 0.000676
destGRR                                   -24.648547   7.256882  -3.396575 0.000683
destGSO                                   -27.791331   8.186192  -3.394903 0.000687
destIAD                                   -32.407962   9.550812  -3.393215 0.000691
destOKC                                   -10.626435   3.139739  -3.384496 0.000713
destPIT                                   -30.140890   8.909258  -3.383098 0.000717
destDCA                                   -32.545897   9.625597  -3.381182 0.000722
destMCI                                   -14.798414   4.379165  -3.379277 0.000727
destALB                                   -33.767488   9.997762  -3.377505 0.000732
destPHL                                   -34.872031  10.335187  -3.374108 0.000741
destCHS                                   -24.003318   7.115993  -3.373151 0.000743
destIND                                   -23.582074   6.995318  -3.371123 0.000749
destSTL                                   -19.054904   5.660461  -3.366317 0.000762
destPVD                                   -33.332083   9.908856  -3.363868 0.000769
destANC                                    36.554722  10.888763   3.357105 0.000788
destMHT                                   -32.248146   9.615996  -3.353594 0.000798
destSYR                                   -32.442780   9.675578  -3.353059 0.000799
destORF                                   -30.723323   9.167680  -3.351265 0.000805
destCMH                                   -27.023263   8.067612  -3.349599 0.000810
destBNA                                   -21.381935   6.388039  -3.347183 0.000817
destSDF                                   -23.471800   7.027043  -3.340210 0.000837
destRDU                                   -27.895202   8.360245  -3.336649 0.000848
destTVC                                   -23.763734   7.123077  -3.336161 0.000850
destSAV                                   -22.145147   6.646547  -3.331828 0.000863
destMDW                                   -22.017052   6.613415  -3.329150 0.000871
destACK                                   -32.386998   9.753827  -3.320440 0.000899
destMKE                                   -21.556521   6.534602  -3.298827 0.000971
destDTW                                   -26.134652   7.928589  -3.296255 0.000980
destCLT                                   -25.088232   7.674413  -3.269075 0.001079
destJAX                                   -19.502019   5.989172  -3.256213 0.001129
destORD                                   -21.244774   6.565174  -3.235981 0.001213
destMCO                                   -17.147920   5.306618  -3.231422 0.001232
destMSY                                   -12.718760   3.935982  -3.231408 0.001232
destMSN                                   -19.745453   6.122372  -3.225131 0.001260
destMVY                                   -31.958595   9.911091  -3.224528 0.001262
day                                         0.075847   0.023801   3.186663 0.001440
destATL                                   -20.349736   6.406683  -3.176329 0.001492
destRSW                                   -14.406148   4.545223  -3.169514 0.001527
destSRQ                                   -15.035777   4.752239  -3.163935 0.001557
destTPA                                   -15.652896   4.951828  -3.161034 0.001573
destBUR                                    12.507966   3.973579   3.147783 0.001646
destCAE                                   -22.661801   7.428543  -3.050639 0.002284
destMSP                                   -14.801747   4.870956  -3.038776 0.002376
destMEM                                   -15.840986   5.227838  -3.030122 0.002445
destFLL                                   -13.585753   4.566169  -2.975307 0.002928
destMIA                                   -13.114128   4.444244  -2.950812 0.003170
destPSE                                    -4.940578   1.678873  -2.942794 0.003253
destPBI                                   -13.976366   4.805236  -2.908570 0.003632
(Intercept)                                16.474044   5.670479   2.905230 0.003671
destAUS                                    -5.873576   2.038240  -2.881690 0.003956
carrierB6                                  -0.654102   0.227007  -2.881420 0.003960
destDFW                                    -7.889899   2.756116  -2.862688 0.004201
destMYR                                   -21.926351   7.794817  -2.812940 0.004910
originLGA                                  -0.325794   0.115862  -2.811914 0.004926
destIAH                                    -7.258532   2.613026  -2.777827 0.005473
destBQN                                    -4.859601   1.759015  -2.762683 0.005734
destHOU                                    -6.906619   2.546684  -2.712005 0.006689
humid                                       0.417871   0.155521   2.686914 0.007213
manufacturerGULFSTREAM AEROSPACE            8.169688   3.182253   2.567265 0.010252
manufacturerCESSNA                          4.567610   1.811097   2.522013 0.011670
destBZN                                     5.625552   2.281507   2.465718 0.013675
precip_flag1                               -9.363342   3.876804  -2.415222 0.015727
temp_flag1                                  8.517235   3.583399   2.376859 0.017462
carrierYV                                  -1.410746   0.595048  -2.370812 0.017751
manufacturerLEARJET INC                     9.621229   4.098480   2.347511 0.018901
destSAT                                    -4.082388   1.761550  -2.317497 0.020478
carrierUA                                   0.589784   0.254952   2.313314 0.020707
destEYW                                   -11.192190   4.855385  -2.305109 0.021162
carrierFL                                   0.948807   0.417663   2.271705 0.023106
manufacturerMCDONNELL DOUGLAS CORPORATION   7.130518   3.144929   2.267307 0.023373
carrierOO                                  -4.676371   2.080031  -2.248222 0.024564
month                                       0.055963   0.025119   2.227950 0.025886
engineReciprocating                        -4.784441   2.155649  -2.219490 0.026455
engineTurbo-jet                            -7.579155   3.523834  -2.150826 0.031492
manufacturerBOEING                          6.655788   3.121857   2.131996 0.033009
manufacturerBARKER JACK L                   4.156889   1.949770   2.131989 0.033010
manufacturerCANADAIR LTD                   10.020777   4.719325   2.123350 0.033727
manufacturerDEHAVILLAND                     5.277486   2.489152   2.120194 0.033992
destPSP                                     9.000603   4.426308   2.033434 0.042011
manufacturerMCDONNELL DOUGLAS               6.307716   3.121992   2.020414 0.043343
manufacturerPIPER                           4.028235   2.033192   1.981236 0.047567
manufacturerMCDONNELL DOUGLAS AIRCRAFT CO   6.192869   3.126076   1.981036 0.047590
engineTurbo-fan                            -6.970145   3.522649  -1.978666 0.047856
manufacturerPAIR MIKE E                     5.954488   3.056590   1.948082 0.051408
manufacturerCIRRUS DESIGN CORP              3.649312   1.879395   1.941748 0.052170
manufacturerAIRBUS INDUSTRIE                5.928450   3.122708   1.898496 0.057633
destSTT                                    -2.956627   1.572582  -1.880110 0.060096
destSJU                                    -2.898323   1.599828  -1.811647 0.070043
manufacturerEMBRAER                         5.378862   3.116909   1.725704 0.084403
destSBN                                   -15.570339   9.034869  -1.723361 0.084826
manufacturerAIRBUS                          5.285531   3.124349   1.691722 0.090702
wind_dir_flag1                              0.269529   0.159642   1.688332 0.091350
manufacturerLEBLANC GLENN T                 4.512985   2.739959   1.647100 0.099540
destMTJ                                     5.184644   3.150881   1.645458 0.099878
manufacturerFRIEDEMANN JON                  3.889750   2.392071   1.626102 0.103931
manufacturerBOMBARDIER INC                  4.655030   3.120928   1.491553 0.135819
destDEN                                    -2.165776   1.518672  -1.426099 0.153843
manufacturerCANADAIR                        4.355101   3.145879   1.384383 0.166244
manufacturerKILDALL GARY                    2.862667   2.445757   1.170462 0.241817
manufacturerAMERICAN AIRCRAFT INC           3.066792   2.683506   1.142830 0.253112
manufacturerMARZ BARRY                      2.829639   2.587439   1.093606 0.274130
manufacturerAVIONS MARCEL DASSAULT          6.754935   6.699339   1.008299 0.313313
manufacturerBEECH                           3.431401   3.551823   0.966096 0.333998
manufacturerJOHN G HESS                    -4.810782   5.388356  -0.892811 0.371960
manufacturerSIKORSKY                        3.186564   3.678961   0.866159 0.386405
manufacturerBELL                            2.610957   3.284993   0.794814 0.426724
type_flag1                                 -0.203922   0.271119  -0.752150 0.451962
manufacturerDOUGLAS                         4.008806   5.632419   0.711738 0.476629
wind_dir                                    0.018733   0.027026   0.693150 0.488217
sched_arr_time_minute                      -0.013804   0.024404  -0.565633 0.571644
carrierVX                                   0.181052   0.323759   0.559219 0.576013
year.y_flag1                               -0.102593   0.199432  -0.514424 0.606957
manufacturerLAMBERT RICHARD                 1.058252   2.476434   0.427329 0.669141
manufacturerHURLEY JAMES LARRY             -1.997386   4.928047  -0.405310 0.685251
carrierF9                                   0.242613   0.637308   0.380684 0.703438
destHDN                                     1.137227   3.190730   0.356416 0.721530
engines                                    -0.051607   0.146845  -0.351438 0.725260
destEGE                                     0.431238   1.375901   0.313422 0.753960
wind_speed_flag1                            0.449983   1.446992   0.310978 0.755818
typeFixed wing single engine                0.606625   2.103014   0.288455 0.772999
dewp                                        0.040676   0.302037   0.134670 0.892873
manufacturerAVIAT AIRCRAFT INC             -0.501995   3.968705  -0.126488 0.899346
temp                                        0.023006   0.260704   0.088244 0.929683
manufacturerROBINSON HELICOPTER CO          0.248651   3.245307   0.076619 0.938927
typeRotorcraft                             -0.198373   4.095669  -0.048435 0.961370
> lm_test_df <- test_df
> 
> in_test_but_not_train <- setdiff(unique(lm_test_df$model), unique(train_df$model))
> lm_test_df <- lm_test_df[ !lm_test_df$model %in% in_test_but_not_train, ]
> 
> in_test_but_not_train <- setdiff(unique(lm_test_df$dest), unique(train_df$dest))
> lm_test_df <- lm_test_df[ !lm_test_df$dest %in% in_test_but_not_train, ]
> 
> preds = predict(model, newdata=lm_test_df)
prediction from a rank-deficient fit may be misleading
> rmse = sqrt(mean((lm_test_df$dep_delay - preds)^2))
> rmse
[1] 8.003373
> set.seed(42)
> library(gbm)
Loaded gbm 2.1.5
> model <- gbm(dep_delay ~ ., data=train_df,
+               n.trees=1000, shrinkage=0.003) # default shrinkage = 0.1
Distribution not specified, assuming gaussian ...
> preds = predict(model, newdata=test_df, n.trees=1000)
> rmse = sqrt(mean((test_df$dep_delay - preds)^2))
> rmse
[1] 8.087401
> summary(model)
> model <- gbm(dep_delay ~ ., data=train_df,
+               n.trees=1000, shrinkage=0.01) # default shrinkage = 0.1
Distribution not specified, assuming gaussian ...
> preds = predict(model, newdata=test_df, n.trees=1000)
> rmse = sqrt(mean((test_df$dep_delay - preds)^2))
> rmse
[1] 7.980812
> summary(model)
> rmse = sqrt(mean((test_df$dep_delay - preds)^2))
> rmse
[1] 7.980812
> library(EZtune)
> response <- DF$dep_delay
> eztune_df <- DF
> eztune_df$dep_delay <- NULL
> eztune_obj <- eztune(eztune_df, response, method = "gbm", optimizer = "hjn", fast = TRUE,
+ cross = NULL)
variable 20: dst has no variation.variable 35: temp_flag has no variation.variable 37: wind_speed_flag has no variation.variable 38: precip_flag has no variation.variable 40: name_flag has no variation.
> model <- lm(dep_delay ~ ., data=train_df)
> model_without_dep <-  lm(dep_delay ~ .-dep, data=train_df)
Error in eval(predvars, data, env) : object 'dep' not found
> model <- lm(dep_delay ~ ., data=train_df)
> model_without_dep <-  lm(dep_delay ~ .-dest, data=train_df)
> anova(model, model_without_dep)
Analysis of Variance Table

Model 1: dep_delay ~ month + day + carrier + origin + dest + distance + 
    temp + dewp + humid + wind_dir + wind_speed + precip + pressure + 
    visib + name + lat + lon + alt + tz + dst + tzone + year.y + 
    type + manufacturer + model + engines + seats + engine + 
    sched_arr_time_minute + sched_arr_time_num_minute + sched_dep_time_minute + 
    sched_dep_time_num_minute + sched_air_time + dep_delay_flag + 
    temp_flag + wind_dir_flag + wind_speed_flag + precip_flag + 
    pressure_flag + name_flag + year.y_flag + type_flag
Model 2: dep_delay ~ (month + day + carrier + origin + dest + distance + 
    temp + dewp + humid + wind_dir + wind_speed + precip + pressure + 
    visib + name + lat + lon + alt + tz + dst + tzone + year.y + 
    type + manufacturer + model + engines + seats + engine + 
    sched_arr_time_minute + sched_arr_time_num_minute + sched_dep_time_minute + 
    sched_dep_time_num_minute + sched_air_time + dep_delay_flag + 
    temp_flag + wind_dir_flag + wind_speed_flag + precip_flag + 
    pressure_flag + name_flag + year.y_flag + type_flag) - dest
  Res.Df     RSS Df Sum of Sq     F    Pr(>F)    
1 113488 7240975                                 
2 113491 7242239 -3   -1263.7 6.602 0.0001863 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> summary <- round(summary(model)$coefficients,6)
> sorteddf <- summary[order(summary[,ncol(summary)]),]
> head(sorteddf)
            Estimate Std. Error    t value Pr(>|t|)
carrierFL   4.615319   0.887510   5.200301        0
carrierUA   2.440853   0.484369   5.039237        0
originJFK   1.037568   0.117779   8.809419        0
wind_speed  0.291278   0.027929  10.429081        0
precip      0.206814   0.029257   7.068777        0
pressure   -0.294549   0.027059 -10.885462        0
> no_duplicate <- data_set[!duplicated(as.list(data_set
+ 

> hist(original_data$dep_delay)
> hist(original_data[original_data$dep_delay < 30,])
Error in plot.new() : figure margins too large
> hist(original_data[original_data$dep_delay < 30,])
Error in plot.new() : figure margins too large
> original_data[original_data$dep_delay < 30,]
# A tibble: 170,645 x 43
   year.x month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time arr_delay carrier
    <dbl> <dbl> <dbl>    <dbl>          <dbl>     <dbl>    <dbl>          <dbl>     <dbl> <chr>  
 1   2013    11     7      600            600         0      826            825         1 WN     
 2   2013    10    30     1252           1250         2     1356           1400        -4 AA     
 3   2013    12    18     1723           1715         8     2008           2020       -12 DL     
 4   2013    11    20     2029           2030        -1     2141           2205       -24 WN     
 5   2013    10    21     1620           1625        -5     1818           1831       -13 DL     
 6   2013    11     7      852            900        -8     1139           1157       -18 B6     
 7   2013     9    29     1519           1529       -10     1639           1649       -10 EV     
 8   2013    12    21     1526           1530        -4     1654           1710       -16 EV     
 9   2013    11     7     1650           1650         0     1910           1906         4 9E     
10   2013     3    31     1652           1700        -8     1810           1821       -11 US     
# … with 170,635 more rows, and 33 more variables: flight <dbl>, tailnum <chr>, origin <chr>,
#   dest <chr>, air_time <dbl>, distance <dbl>, hour <dbl>, minute <dbl>, time_hour <dttm>,
#   temp <dbl>, dewp <dbl>, humid <dbl>, wind_dir <dbl>, wind_speed <dbl>, wind_gust <dbl>,
#   precip <dbl>, pressure <dbl>, visib <dbl>, name <chr>, lat <dbl>, lon <dbl>, alt <dbl>,
#   tz <dbl>, dst <chr>, tzone <chr>, year.y <dbl>, type <chr>, manufacturer <chr>, model <chr>,
#   engines <dbl>, seats <dbl>, speed <dbl>, engine <chr>
> hist(original_data[original_data$dep_delay < 30,]$dep_delay)
> hist(original_data[original_data$dep_delay > 30,]$dep_delay)
> hist(original_data[original_data$dep_delay > 30,]$dep_delay)
> hist(original_data[original_data$dep_delay > 20,]$dep_delay)
> hist(original_data[original_data$dep_delay > 200,]$dep_delay)
> hist(original_data[original_data$dep_delay > 400,]$dep_delay)
> DF[sapply(DF, is.character)] <- lapply(DF[sapply(DF, is.character)], 
+                                        as.factor)
> DF$flight <- as.factor(DF$flight)
Error in `$<-.data.frame`(`*tmp*`, flight, value = integer(0)) : 
  replacement has 0 rows, data has 170645
> knitr::opts_chunk$set(echo = TRUE)
> library(tidyverse)
> library(nycflights13)
> library(Hmisc)
> set.seed(42)
> original_data <- read_csv("fltrain.csv.gz")
Parsed with column specification:
cols(
  .default = col_double(),
  carrier = col_character(),
  tailnum = col_character(),
  origin = col_character(),
  dest = col_character(),
  time_hour = col_datetime(format = ""),
  name = col_character(),
  dst = col_character(),
  tzone = col_character(),
  type = col_character(),
  manufacturer = col_character(),
  model = col_character(),
  engine = col_character()
)
See spec(...) for full column specifications.
> DF <- original_data
> DF[sapply(DF, is.character)] <- lapply(DF[sapply(DF, is.character)], 
+                                        as.factor)
> DF$flight <- as.factor(DF$flight)
> str(DF)
Classes ‘spec_tbl_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	200000 obs. of  43 variables:
 $ year.x        : num  2013 2013 2013 2013 2013 ...
 $ month         : num  11 10 12 11 10 11 9 12 11 3 ...
 $ day           : num  7 30 18 20 21 7 29 21 7 31 ...
 $ dep_time      : num  600 1252 1723 2029 1620 ...
 $ sched_dep_time: num  600 1250 1715 2030 1625 ...
 $ dep_delay     : num  0 2 8 -1 -5 -8 -10 -4 0 -8 ...
 $ arr_time      : num  826 1356 2008 2141 1818 ...
 $ sched_arr_time: num  825 1400 2020 2205 1831 ...
 $ arr_delay     : num  1 -4 -12 -24 -13 -18 -10 -16 4 -11 ...
 $ carrier       : Factor w/ 16 levels "9E","AA","AS",..: 15 2 5 15 5 4 6 6 1 13 ...
 $ flight        : Factor w/ 3672 levels "1","2","3","4",..: 1525 147 1400 2343 1860 24 3083 3351 2070 1840 ...
 $ tailnum       : Factor w/ 3957 levels "D942DN","N0EGMQ",..: 1437 1226 836 565 756 2459 204 2890 646 3008 ...
 $ origin        : Factor w/ 3 levels "EWR","JFK","LGA": 3 2 3 1 3 1 1 3 2 3 ...
 $ dest          : Factor w/ 104 levels "ABQ","ACK","ALB",..: 5 12 54 55 33 54 59 59 27 29 ...
 $ air_time      : num  123 44 133 107 90 136 110 118 101 47 ...
 $ distance      : num  762 187 950 711 502 937 725 738 589 214 ...
 $ hour          : num  6 12 17 20 16 9 15 15 16 17 ...
 $ minute        : num  0 50 15 30 25 0 29 30 50 0 ...
 $ time_hour     : POSIXct, format: "2013-11-07 11:00:00" "2013-10-30 16:00:00" "2013-12-18 22:00:00" ...
 $ temp          : num  63 59 34 37 63 ...
 $ dewp          : num  55.9 46.9 17.1 18 41 ...
 $ humid         : num  77.8 64.2 49.5 45.6 44.5 ...
 $ wind_dir      : num  210 240 270 20 160 240 180 190 320 140 ...
 $ wind_speed    : num  13.81 9.21 17.26 5.75 13.81 ...
 $ wind_gust     : num  NA NA 21.9 NA NA ...
 $ precip        : num  0 0 0 0 0 0 0 0 0 0 ...
 $ pressure      : num  1011 1025 1020 1036 1017 ...
 $ visib         : num  10 10 10 10 10 10 10 10 10 10 ...
 $ name          : Factor w/ 100 levels "Akron Canton Regional Airport",..: 37 31 67 17 26 67 32 32 19 79 ...
 $ lat           : num  33.6 42.4 28.4 41.8 42.2 ...
 $ lon           : num  -84.4 -71 -81.3 -87.8 -83.4 ...
 $ alt           : num  1026 19 96 620 645 ...
 $ tz            : num  -5 -5 -5 -6 -5 -5 -6 -6 -5 -5 ...
 $ dst           : Factor w/ 2 levels "A","N": 1 1 1 1 1 1 1 1 1 1 ...
 $ tzone         : Factor w/ 7 levels "America/Anchorage",..: 5 5 5 2 5 5 2 2 5 5 ...
 $ year.y        : num  2001 NA 2002 2006 1992 ...
 $ type          : Factor w/ 3 levels "Fixed wing multi engine",..: 1 NA 1 1 1 1 1 1 1 1 ...
 $ manufacturer  : Factor w/ 35 levels "AGUSTA SPA","AIRBUS",..: 10 NA 2 10 3 2 18 11 11 3 ...
 $ model         : Factor w/ 126 levels "150","172E","172M",..: 37 NA 80 37 84 88 106 98 99 79 ...
 $ engines       : num  2 NA 2 2 2 2 2 2 2 2 ...
 $ seats         : num  140 NA 145 140 182 200 55 80 95 179 ...
 $ speed         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ engine        : Factor w/ 6 levels "4 Cycle","Reciprocating",..: 3 NA 3 3 4 3 3 3 3 3 ...
 - attr(*, "spec")=
  .. cols(
  ..   year.x = col_double(),
  ..   month = col_double(),
  ..   day = col_double(),
  ..   dep_time = col_double(),
  ..   sched_dep_time = col_double(),
  ..   dep_delay = col_double(),
  ..   arr_time = col_double(),
  ..   sched_arr_time = col_double(),
  ..   arr_delay = col_double(),
  ..   carrier = col_character(),
  ..   flight = col_double(),
  ..   tailnum = col_character(),
  ..   origin = col_character(),
  ..   dest = col_character(),
  ..   air_time = col_double(),
  ..   distance = col_double(),
  ..   hour = col_double(),
  ..   minute = col_double(),
  ..   time_hour = col_datetime(format = ""),
  ..   temp = col_double(),
  ..   dewp = col_double(),
  ..   humid = col_double(),
  ..   wind_dir = col_double(),
  ..   wind_speed = col_double(),
  ..   wind_gust = col_double(),
  ..   precip = col_double(),
  ..   pressure = col_double(),
  ..   visib = col_double(),
  ..   name = col_character(),
  ..   lat = col_double(),
  ..   lon = col_double(),
  ..   alt = col_double(),
  ..   tz = col_double(),
  ..   dst = col_character(),
  ..   tzone = col_character(),
  ..   year.y = col_double(),
  ..   type = col_character(),
  ..   manufacturer = col_character(),
  ..   model = col_character(),
  ..   engines = col_double(),
  ..   seats = col_double(),
  ..   speed = col_double(),
  ..   engine = col_character()
  .. )
> library(lubridate)
> DF$sched_arr_time_posix <- as.POSIXct(str_pad(as.character(DF$sched_arr_time), 4, pad="0"),format="%H%M")
> DF$sched_arr_time_hour <- hour(DF$sched_arr_time_posix)
> DF$sched_arr_time_minute <- minute(DF$sched_arr_time_posix)
> 
> #num minute is number of minutes since start of day for scheduled arrival time
> DF$sched_arr_time_num_minute <- 60*DF$sched_arr_time_hour + DF$sched_arr_time_minute
> 
> DF$sched_dep_time_posix <- as.POSIXct(str_pad(as.character(DF$sched_dep_time),4 , pad="0"),format="%H%M")
> DF$sched_dep_time_hour <- hour(DF$sched_dep_time_posix)
> DF$sched_dep_time_minute <- minute(DF$sched_dep_time_posix)
> #num minute is number of minutes since start of day for scheduled depival time
> DF$sched_dep_time_num_minute <- 60*DF$sched_dep_time_hour + DF$sched_dep_time_minute
> select(original_data, time_hour, sched_dep_time, sched_arr_time, tz, tzone)
> select(DF, sched_arr_time, sched_arr_time_hour)
> DF$sched_air_time <- DF$sched_arr_time_posix - DF$sched_dep_time_posix
> drops <- c('sched_arr_time_posix', 'sched_arr_time_hour', 'sched_dep_time_posix', 'sched_dep_time_hour', 'sched_dep_time', 'sched_arr_time', 'hour', 'time', 'minute', 'time_hour' )
> DF <- DF[ , !(names(DF) %in% drops)]
> drops <- c("dep_time", "arr_time", "air_time", "arr_delay", "year.x", 'tailnum')
> DF <- DF[ , !(names(DF) %in% drops)]
> DF
> model <- lm(dep_delay ~ ., data=train_df)
> model_without_dep <-  lm(dep_delay ~ .-dest, data=train_df)
> anova(model, model_without_dep)
Analysis of Variance Table

Model 1: dep_delay ~ month + day + carrier + origin + dest + distance + 
    temp + dewp + humid + wind_dir + wind_speed + precip + pressure + 
    visib + name + lat + lon + alt + tz + dst + tzone + year.y + 
    type + manufacturer + model + engines + seats + engine + 
    sched_arr_time_minute + sched_arr_time_num_minute + sched_dep_time_minute + 
    sched_dep_time_num_minute + sched_air_time + dep_delay_flag + 
    temp_flag + wind_dir_flag + wind_speed_flag + precip_flag + 
    pressure_flag + name_flag + year.y_flag + type_flag
Model 2: dep_delay ~ (month + day + carrier + origin + dest + distance + 
    temp + dewp + humid + wind_dir + wind_speed + precip + pressure + 
    visib + name + lat + lon + alt + tz + dst + tzone + year.y + 
    type + manufacturer + model + engines + seats + engine + 
    sched_arr_time_minute + sched_arr_time_num_minute + sched_dep_time_minute + 
    sched_dep_time_num_minute + sched_air_time + dep_delay_flag + 
    temp_flag + wind_dir_flag + wind_speed_flag + precip_flag + 
    pressure_flag + name_flag + year.y_flag + type_flag) - dest
  Res.Df     RSS Df Sum of Sq     F    Pr(>F)    
1 113488 7240975                                 
2 113491 7242239 -3   -1263.7 6.602 0.0001863 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> summary <- round(summary(model)$coefficients,6)
> sorteddf <- summary[order(summary[,ncol(summary)]),]
> head(sorteddf)
            Estimate Std. Error    t value Pr(>|t|)
carrierFL   4.615319   0.887510   5.200301        0
carrierUA   2.440853   0.484369   5.039237        0
originJFK   1.037568   0.117779   8.809419        0
wind_speed  0.291278   0.027929  10.429081        0
precip      0.206814   0.029257   7.068777        0
pressure   -0.294549   0.027059 -10.885462        0
> 
> inflm.SR <- influence.measures(model)
